### ISSUE TITLE
cep promisse

### ISSUE THREAD

**Issue by sidneysil** [maeldz/inter-clone#1]
fala amigo vc tem os codigos pra eu dar uma olhada pra oq vc fez aqui..https://matheuskuster.github.io/react-cep-promise/

**Comment by maeldz** [comment]
Boa tarde @sidneysil creio que aqui não seja o espaço adequado para se tirar dúvidas, pra isso você pode usar o inbox do facebook mesmo. Mas de qualquer forma não consegui entender sua dúvida e nem a relação desta lib com o projeto.

**Comment by sidneysil** [comment]
fala amigo envia seu zap ou inbox do facebook por favor o link,
